version: '3.2'
services:

  mongo:
    image: mongo:latest
    ports:
      - 27017

  backend:
      build: ../JADBack/.
      image: jadpmanager/backend:latest
      environment:
        - SECRET=thisisasecretkeyforjwtoken
        - PORT=3000
        - MONGODB_URL=mongodb://mongo:27017/nest
      ports:
        - 3000

  frontend:
      build: ../JADfront/.
      image: jadpmanager/frontend:latest
      ports:
        - 80

  loadbalancer:
      build: .
      image: jadpmanager/ingress:latest
      links:
          - frontend
          - backend
      ports:
          - '80:80'
