version: '3.2'
services:
  backend:
      image: jadpmanager/backend:latest
      ports:
        - 3000

  frontend:
      image: jadpmanager/frontend:latest
      ports:
        - 80

  loadbalancer:
      image: jadpmanager/ingress:latest
      links:
          - frontend
          - backend
      ports:
          - 80:80
