version: '3.2'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017

  backend:
      image: jadpmanager/backend:latest
      environment:
        - SECRET=Thisisasecretkeyforjwtoken
        - PORT=3000
        - MONGODB_URL=mongodb://mongo:27017/nest
      links:
        - mongo
      ports:
        - 3000    

  frontend:
      image: jadpmanager/frontend:latest
      ports:
        - 80

  loadbalancer:
      image: jadpmanager/ingress:latest
      links:
          - frontend
          - backend
      ports:
          - 80:80
